In [164]:
import pandas as pd

In [165]:
url = "https://fbref.com/en/players/fed7cb61/matchlogs/2022-2023/misc/Kai-Havertz-Match-Logs"

In [166]:
stats = pd.read_html(url)

In [167]:
df = stats[0]

In [168]:
pd.set_option("display.max_columns", None)

In [169]:
df

   Unnamed: 0_level_0 Unnamed: 1_level_0   Unnamed: 2_level_0  \
                 Date                Day                 Comp
0          2022-06-04                Sat  UEFA Nations League
1          2022-06-07                Tue  UEFA Nations League
2          2022-06-11                Sat  UEFA Nations League
3          2022-06-14                Tue  UEFA Nations League
4          2022-08-06                Sat       Premier League
5          2022-08-14                Sun       Premier League
6          2022-08-21                Sun       Premier League
7          2022-08-27                Sat       Premier League
8          2022-08-30                Tue       Premier League
9          2022-09-03                Sat       Premier League
10         2022-09-06                Tue         Champions Lg
11         2022-09-14                Wed         Champions Lg
12         2022-09-23                Fri  UEFA Nations League
13         2022-09-26                Mon  UEFA Nations League
14         2022-10-01                Sat       Premier League
15         2022-10-05                Wed         Champions Lg
16         2022-10-08                Sat       Premier League
17         2022-10-11                Tue         Champions Lg
18         2022-10-16                Sun       Premier League
19         2022-10-19                Wed       Premier League
20         2022-10-22                Sat       Premier League
21         2022-10-25                Tue         Champions Lg
22         2022-10-29                Sat       Premier League
23         2022-11-02                Wed         Champions Lg
24         2022-11-06                Sun       Premier League
25         2022-11-09                Wed              EFL Cup
26         2022-11-12                Sat       Premier League
27         2022-11-16                Wed       Friendlies (M)
28         2022-11-23                Wed            World Cup
29         2022-11-27                Sun            World Cup
30         2022-12-01                Thu            World Cup
31         2022-12-27                Tue       Premier League
32         2023-01-01                Sun       Premier League
33         2023-01-05                Thu       Premier League
34         2023-01-08                Sun               FA Cup
35         2023-01-12                Thu       Premier League
36         2023-01-15                Sun       Premier League
37         2023-01-21                Sat       Premier League
38         2023-02-03                Fri       Premier League
39         2023-02-11                Sat       Premier League
40         2023-02-15                Wed         Champions Lg
41         2023-02-18                Sat       Premier League
42         2023-02-26                Sun       Premier League
43         2023-03-04                Sat       Premier League
44         2023-03-07                Tue         Champions Lg
45         2023-03-11                Sat       Premier League
46         2023-03-18                Sat       Premier League
47         2023-03-25                Sat       Friendlies (M)
48         2023-04-01                Sat       Premier League
49         2023-04-04                Tue       Premier League
50         2023-04-08                Sat       Premier League
51         2023-04-12                Wed         Champions Lg
52                NaN                NaN                  NaN
53         2023-04-18                Tue         Champions Lg
54                NaN                NaN                  NaN
55         2023-05-02                Tue       Premier League
56         2023-05-06                Sat       Premier League
57         2023-05-13                Sat       Premier League
58         2023-05-21                Sun       Premier League
59         2023-05-25                Thu       Premier League
60         2023-05-28                Sun       Premier League
61         2023-06-12                Mon       Friendlies (M)
62         2023-06-16                Fri       Friendlies (M)
63         2023-06-20                Tue       Friendlies (M)
64                NaN                NaN                  NaN

    Unnamed: 3_level_0 Unnamed: 4_level_0 Unnamed: 5_level_0  \
                 Round              Venue             Result
0             League A               Away              D 1–1
1             League A               Home              D 1–1
2             League A               Away              D 1–1
3             League A               Home              W 5–2
4          Matchweek 1               Away              W 1–0
5          Matchweek 2               Home              D 2–2
6          Matchweek 3               Away              L 0–3
7          Matchweek 4               Home              W 2–1
8          Matchweek 5               Away              L 1–2
9          Matchweek 6               Home              W 2–1
10         Group stage               Away              L 0–1
11         Group stage               Home              D 1–1
12            League A               Home              L 0–1
13            League A               Away              D 3–3
14         Matchweek 9               Away              W 2–1
15         Group stage               Home              W 3–0
16        Matchweek 10               Home              W 3–0
17         Group stage               Away              W 2–0
18        Matchweek 11               Away              W 2–0
19        Matchweek 12               Away              D 0–0
20        Matchweek 13               Home              D 1–1
21         Group stage               Away              W 2–1
22        Matchweek 14               Away              L 1–4
23         Group stage               Home              W 2–1
24        Matchweek 15               Home              L 0–1
25         Third round               Away              L 0–2
26        Matchweek 16               Away              L 0–1
27      Friendlies (M)            Neutral              W 1–0
28         Group stage            Neutral              L 1–2
29         Group stage            Neutral              D 1–1
30         Group stage            Neutral              W 4–2
31        Matchweek 17               Home              W 2–0
32        Matchweek 18               Away              D 1–1
33        Matchweek 19               Home              L 0–1
34  Third round proper               Away              L 0–4
35         Matchweek 7               Away              L 1–2
36        Matchweek 20               Home              W 1–0
37        Matchweek 21               Away              D 0–0
38        Matchweek 22               Home              D 0–0
39        Matchweek 23               Away              D 1–1
40         Round of 16               Away              L 0–1
41        Matchweek 24               Home              L 0–1
42        Matchweek 25               Away              L 0–2
43        Matchweek 26               Home              W 1–0
44         Round of 16               Home              W 2–0
45        Matchweek 27               Away              W 3–1
46        Matchweek 28               Home              D 2–2
47      Friendlies (M)               Home              W 2–0
48        Matchweek 29               Home              L 0–2
49         Matchweek 8               Home              D 0–0
50        Matchweek 30               Away              L 0–1
51      Quarter-finals               Away              L 0–2
52                 NaN                NaN                NaN
53      Quarter-finals               Home              L 0–2
54                 NaN                NaN                NaN
55        Matchweek 34               Away              L 1–3
56        Matchweek 35               Away              W 3–1
57        Matchweek 36               Home              D 2–2
58        Matchweek 37               Away              L 0–1
59        Matchweek 32               Away              L 1–4
60        Matchweek 38               Home              D 1–1
61      Friendlies (M)               Home              D 3–3
62      Friendlies (M)               Away              L 0–1
63      Friendlies (M)               Home              L 0–2
64                 NaN                NaN           19-16-24

   Unnamed: 6_level_0 Unnamed: 7_level_0 Unnamed: 8_level_0  \
                Squad           Opponent              Start
0          de Germany           it Italy                  N
1          de Germany        eng England                  Y
2          de Germany         hu Hungary                  Y
3          de Germany           it Italy                  N
4             Chelsea            Everton                  Y
5             Chelsea          Tottenham                  Y
6             Chelsea       Leeds United                  Y
7             Chelsea     Leicester City                  Y
8             Chelsea        Southampton                  Y
9             Chelsea           West Ham                  N
10        eng Chelsea   hr Dinamo Zagreb                  Y
11        eng Chelsea     at RB Salzburg                  Y
12         de Germany         hu Hungary                  N
13         de Germany        eng England                  Y
14            Chelsea     Crystal Palace                  Y
15        eng Chelsea           it Milan                  N
16            Chelsea             Wolves                  Y
17        eng Chelsea           it Milan                  N
18            Chelsea        Aston Villa                  Y
19            Chelsea          Brentford                  Y
20            Chelsea     Manchester Utd                  N
21        eng Chelsea     at RB Salzburg                  Y
22            Chelsea           Brighton                  Y
23        eng Chelsea   hr Dinamo Zagreb                  Y
24            Chelsea            Arsenal                  Y
25            Chelsea    Manchester City                  N
26            Chelsea      Newcastle Utd                  N
27         de Germany            om Oman                  Y
28         de Germany           jp Japan                  Y
29         de Germany           es Spain                  N
30         de Germany      cr Costa Rica                  N
31            Chelsea        Bournemouth                  Y
32            Chelsea    Nott'ham Forest                  Y
33            Chelsea    Manchester City                  Y
34            Chelsea    Manchester City                  Y
35            Chelsea             Fulham                  Y
36            Chelsea     Crystal Palace                  Y
37            Chelsea          Liverpool                  Y
38            Chelsea             Fulham                  Y
39            Chelsea           West Ham                  Y
40        eng Chelsea        de Dortmund                  Y
41            Chelsea        Southampton                  N
42            Chelsea          Tottenham                  Y
43            Chelsea       Leeds United                  Y
44        eng Chelsea        de Dortmund                  Y
45            Chelsea     Leicester City                  Y
46            Chelsea            Everton                  Y
47         de Germany            pe Peru                  Y
48            Chelsea        Aston Villa                  Y
49            Chelsea          Liverpool                  Y
50            Chelsea             Wolves                  Y
51        eng Chelsea     es Real Madrid                  N
52                NaN                NaN                NaN
53        eng Chelsea     es Real Madrid                  Y
54                NaN                NaN                NaN
55            Chelsea            Arsenal                  N
56            Chelsea        Bournemouth                  Y
57            Chelsea    Nott'ham Forest                  N
58            Chelsea    Manchester City                  Y
59            Chelsea     Manchester Utd                  Y
60            Chelsea      Newcastle Utd                  Y
61         de Germany         ua Ukraine                  N
62         de Germany          pl Poland                  Y
63         de Germany        co Colombia                  Y
64                NaN                NaN              46/59

                     Unnamed: 9_level_0                  Unnamed: 10_level_0  \
                                    Pos                                  Min
0                                   NaN                                   21
1                                    FW                                   90
2                                    AM                                   84
3   On matchday squad, but did not play  On matchday squad, but did not play
4                                    LW                                   74
5                                    FW                                   89
6                                    FW                                   90
7                                    FW                                   90
8                                    FW                                   65
9                                    RW                                   19
10                                   RW                                   90
11                                   FW                                   65
12                                  NaN                                   22
13                                   FW                                   89
14                                AM,RW                                   75
15                                   AM                                   17
16                                FW,AM                                   85
17                                   FW                                   12
18                                   AM                                   45
19                                AM,FW                                   80
20  On matchday squad, but did not play  On matchday squad, but did not play
21                                FW,AM                                   90
22                                FW,CM                                   90
23                                   AM                                   63
24                                   AM                                   63
25                                  NaN                                   16
26                                   FW                                   18
27                                   AM                                   90
28                                   FW                                   78
29  On matchday squad, but did not play  On matchday squad, but did not play
30                                   FW                                   24
31                                   FW                                   90
32                                FW,AM                                   90
33                                AM,FW                                   90
34                                   FW                                   45
35                                   FW                                   90
36                                FW,AM                                   88
37                                   FW                                   80
38                                FW,LM                                   90
39                                   FW                                   90
40                                   FW                                   90
41                                   FW                                   27
42                                FW,RW                                   90
43                                   FW                                   90
44                                   FW                                   90
45                                FW,RW                                   90
46                                RW,FW                                   90
47                                   RW                                   74
48                                AM,FW                                   90
49                                   FW                                   90
50                                   FW                                   60
51                                   FW                                   26
52                                  NaN                                  NaN
53                                   FW                                   76
54                                  NaN                                  NaN
55                                   FW                                   45
56                                   FW                                   83
57                                   FW                                   18
58                                   FW                                   84
59                                   FW                                   63
60                                   FW                                   58
61                                  NaN                                   45
62                                   FW                                   90
63                                   FW                                   78
64                                  NaN                                 4034

                            Performance                                       \
                                   CrdY                                 CrdR
0                                     1                                    0
1                                     0                                    0
2                                     0                                    0
3   On matchday squad, but did not play  On matchday squad, but did not play
4                                     0                                    0
5                                     1                                    0
6                                     0                                    0
7                                     1                                    0
8                                     0                                    0
9                                     1                                    0
10                                    0                                    0
11                                    0                                    0
12                                    0                                    0
13                                    0                                    0
14                                    0                                    0
15                                    0                                    0
16                                    0                                    0
17                                    0                                    0
18                                    0                                    0
19                                    0                                    0
20  On matchday squad, but did not play  On matchday squad, but did not play
21                                    0                                    0
22                                    0                                    0
23                                    0                                    0
24                                    0                                    0
25                                    0                                    0
26                                    0                                    0
27                                    0                                    0
28                                    0                                    0
29  On matchday squad, but did not play  On matchday squad, but did not play
30                                    0                                    0

In [170]:
cleaned_df = df.iloc[:,[0, 1, 2, 4,10, 11, 14]]

In [171]:
pd.set_option("display.max_rows", None)

In [172]:
cleaned_df

   Unnamed: 0_level_0 Unnamed: 1_level_0   Unnamed: 2_level_0  \
                 Date                Day                 Comp
0          2022-06-04                Sat  UEFA Nations League
1          2022-06-07                Tue  UEFA Nations League
2          2022-06-11                Sat  UEFA Nations League
3          2022-06-14                Tue  UEFA Nations League
4          2022-08-06                Sat       Premier League
5          2022-08-14                Sun       Premier League
6          2022-08-21                Sun       Premier League
7          2022-08-27                Sat       Premier League
8          2022-08-30                Tue       Premier League
9          2022-09-03                Sat       Premier League
10         2022-09-06                Tue         Champions Lg
11         2022-09-14                Wed         Champions Lg
12         2022-09-23                Fri  UEFA Nations League
13         2022-09-26                Mon  UEFA Nations League
14         2022-10-01                Sat       Premier League
15         2022-10-05                Wed         Champions Lg
16         2022-10-08                Sat       Premier League
17         2022-10-11                Tue         Champions Lg
18         2022-10-16                Sun       Premier League
19         2022-10-19                Wed       Premier League
20         2022-10-22                Sat       Premier League
21         2022-10-25                Tue         Champions Lg
22         2022-10-29                Sat       Premier League
23         2022-11-02                Wed         Champions Lg
24         2022-11-06                Sun       Premier League
25         2022-11-09                Wed              EFL Cup
26         2022-11-12                Sat       Premier League
27         2022-11-16                Wed       Friendlies (M)
28         2022-11-23                Wed            World Cup
29         2022-11-27                Sun            World Cup
30         2022-12-01                Thu            World Cup
31         2022-12-27                Tue       Premier League
32         2023-01-01                Sun       Premier League
33         2023-01-05                Thu       Premier League
34         2023-01-08                Sun               FA Cup
35         2023-01-12                Thu       Premier League
36         2023-01-15                Sun       Premier League
37         2023-01-21                Sat       Premier League
38         2023-02-03                Fri       Premier League
39         2023-02-11                Sat       Premier League
40         2023-02-15                Wed         Champions Lg
41         2023-02-18                Sat       Premier League
42         2023-02-26                Sun       Premier League
43         2023-03-04                Sat       Premier League
44         2023-03-07                Tue         Champions Lg
45         2023-03-11                Sat       Premier League
46         2023-03-18                Sat       Premier League
47         2023-03-25                Sat       Friendlies (M)
48         2023-04-01                Sat       Premier League
49         2023-04-04                Tue       Premier League
50         2023-04-08                Sat       Premier League
51         2023-04-12                Wed         Champions Lg
52                NaN                NaN                  NaN
53         2023-04-18                Tue         Champions Lg
54                NaN                NaN                  NaN
55         2023-05-02                Tue       Premier League
56         2023-05-06                Sat       Premier League
57         2023-05-13                Sat       Premier League
58         2023-05-21                Sun       Premier League
59         2023-05-25                Thu       Premier League
60         2023-05-28                Sun       Premier League
61         2023-06-12                Mon       Friendlies (M)
62         2023-06-16                Fri       Friendlies (M)
63         2023-06-20                Tue       Friendlies (M)
64                NaN                NaN                  NaN

   Unnamed: 4_level_0                  Unnamed: 10_level_0  \
                Venue                                  Min
0                Away                                   21
1                Home                                   90
2                Away                                   84
3                Home  On matchday squad, but did not play
4                Away                                   74
5                Home                                   89
6                Away                                   90
7                Home                                   90
8                Away                                   65
9                Home                                   19
10               Away                                   90
11               Home                                   65
12               Home                                   22
13               Away                                   89
14               Away                                   75
15               Home                                   17
16               Home                                   85
17               Away                                   12
18               Away                                   45
19               Away                                   80
20               Home  On matchday squad, but did not play
21               Away                                   90
22               Away                                   90
23               Home                                   63
24               Home                                   63
25               Away                                   16
26               Away                                   18
27            Neutral                                   90
28            Neutral                                   78
29            Neutral  On matchday squad, but did not play
30            Neutral                                   24
31               Home                                   90
32               Away                                   90
33               Home                                   90
34               Away                                   45
35               Away                                   90
36               Home                                   88
37               Away                                   80
38               Home                                   90
39               Away                                   90
40               Away                                   90
41               Home                                   27
42               Away                                   90
43               Home                                   90
44               Home                                   90
45               Away                                   90
46               Home                                   90
47               Home                                   74
48               Home                                   90
49               Home                                   90
50               Away                                   60
51               Away                                   26
52                NaN                                  NaN
53               Home                                   76
54                NaN                                  NaN
55               Away                                   45
56               Away                                   83
57               Home                                   18
58               Away                                   84
59               Away                                   63
60               Home                                   58
61               Home                                   45
62               Away                                   90
63               Home                                   78
64                NaN                                 4034

                            Performance
                                   CrdY                                  Fls
0                                     1                                    1
1                                     0                                    1
2                                     0                                    2
3   On matchday squad, but did not play  On matchday squad, but did not play
4                                     0                                    3
5                                     1                                    2
6                                     0                                    3
7                                     1                                    4
8                                     0                                    0
9                                     1                                    0
10                                    0                                    1
11                                    0                                    1
12                                    0                                    0
13                                    0                                    1
14                                    0                                    1
15                                    0                                    0
16                                    0                                    1
17                                    0                                    1
18                                    0                                    2
19                                    0                                    4
20  On matchday squad, but did not play  On matchday squad, but did not play
21                                    0                                    2
22                                    0                                    0
23                                    0                                    0
24                                    0                                    2
25                                    0                                    0
26                                    0                                    0
27                                    0                                  NaN
28                                    0                                    2
29  On matchday squad, but did not play  On matchday squad, but did not play
30                                    0                                    1
31                                    0                                    3
32                                    0                                    3
33                                    0                                    0
34                                    0                                    2
35                                    0                                    2
36                                    0                                    4
37                                    0                                    0
38                                    0                                    2
39                                    0                                    5
40                                    0                                    3
41                                    0                                    1
42                                    1                                    0
43                                    0                                    3
44                                    0                                    3
45                                    0                                    3
46                                    0                                    3
47                                    0                                  NaN
48                                    0                                    1
49                                    0                                    2
50                                    0                                    0
51                                    0                                    1
52                                  NaN                                  NaN
53                                    0                                    0
54                                  NaN                                  NaN
55                                    0                                    0
56                                    0                                    1
57                                    0                                    0
58                                    1                                    3
59                                    0                                    2
60                                    0                                    0
61                                    0                                  NaN
62                                    0                                  NaN
63                                    0                                  NaN
64                                    6                                   82

In [173]:
cleaned_df.columns

MultiIndex([( 'Unnamed: 0_level_0',  'Date'),
            ( 'Unnamed: 1_level_0',   'Day'),
            ( 'Unnamed: 2_level_0',  'Comp'),
            ( 'Unnamed: 4_level_0', 'Venue'),
            ('Unnamed: 10_level_0',   'Min'),
            (        'Performance',  'CrdY'),
            (        'Performance',   'Fls')],
           )

In [174]:
index = cleaned_df.columns.droplevel(0)

In [175]:
cleaned_df.columns = index

In [176]:
cleaned_df.head(10)

,Date,Day,Comp,Venue,Min,CrdY,Fls
0,2022-06-04,Sat,UEFA Nations League,Away,21,1,1
1,2022-06-07,Tue,UEFA Nations League,Home,90,0,1
2,2022-06-11,Sat,UEFA Nations League,Away,84,0,2
3,2022-06-14,Tue,UEFA Nations League,Home,"On matchday squad, but did not play","On matchday squad, but did not play","On matchday squad, but did not play"
4,2022-08-06,Sat,Premier League,Away,74,0,3
5,2022-08-14,Sun,Premier League,Home,89,1,2
6,2022-08-21,Sun,Premier League,Away,90,0,3
7,2022-08-27,Sat,Premier League,Home,90,1,4
8,2022-08-30,Tue,Premier League,Away,65,0,0
9,2022-09-03,Sat,Premier League,Home,19,1,0

In [177]:
cleaned_df = cleaned_df.drop(cleaned_df[cleaned_df["Min"] == "On matchday squad, but did not play"].index)

In [178]:
cleaned_df = cleaned_df.drop(cleaned_df[cleaned_df["Comp"] == 'Friendlies (M)'].index)

In [179]:
cleaned_df = cleaned_df.dropna()

In [180]:
cleaned_df

          Date  Day                 Comp    Venue Min CrdY Fls
0   2022-06-04  Sat  UEFA Nations League     Away  21    1   1
1   2022-06-07  Tue  UEFA Nations League     Home  90    0   1
2   2022-06-11  Sat  UEFA Nations League     Away  84    0   2
4   2022-08-06  Sat       Premier League     Away  74    0   3
5   2022-08-14  Sun       Premier League     Home  89    1   2
6   2022-08-21  Sun       Premier League     Away  90    0   3
7   2022-08-27  Sat       Premier League     Home  90    1   4
8   2022-08-30  Tue       Premier League     Away  65    0   0
9   2022-09-03  Sat       Premier League     Home  19    1   0
10  2022-09-06  Tue         Champions Lg     Away  90    0   1
11  2022-09-14  Wed         Champions Lg     Home  65    0   1
12  2022-09-23  Fri  UEFA Nations League     Home  22    0   0
13  2022-09-26  Mon  UEFA Nations League     Away  89    0   1
14  2022-10-01  Sat       Premier League     Away  75    0   1
15  2022-10-05  Wed         Champions Lg     Home  17    0   0
16  2022-10-08  Sat       Premier League     Home  85    0   1
17  2022-10-11  Tue         Champions Lg     Away  12    0   1
18  2022-10-16  Sun       Premier League     Away  45    0   2
19  2022-10-19  Wed       Premier League     Away  80    0   4
21  2022-10-25  Tue         Champions Lg     Away  90    0   2
22  2022-10-29  Sat       Premier League     Away  90    0   0
23  2022-11-02  Wed         Champions Lg     Home  63    0   0
24  2022-11-06  Sun       Premier League     Home  63    0   2
25  2022-11-09  Wed              EFL Cup     Away  16    0   0
26  2022-11-12  Sat       Premier League     Away  18    0   0
28  2022-11-23  Wed            World Cup  Neutral  78    0   2
30  2022-12-01  Thu            World Cup  Neutral  24    0   1
31  2022-12-27  Tue       Premier League     Home  90    0   3
32  2023-01-01  Sun       Premier League     Away  90    0   3
33  2023-01-05  Thu       Premier League     Home  90    0   0
34  2023-01-08  Sun               FA Cup     Away  45    0   2
35  2023-01-12  Thu       Premier League     Away  90    0   2
36  2023-01-15  Sun       Premier League     Home  88    0   4
37  2023-01-21  Sat       Premier League     Away  80    0   0
38  2023-02-03  Fri       Premier League     Home  90    0   2
39  2023-02-11  Sat       Premier League     Away  90    0   5
40  2023-02-15  Wed         Champions Lg     Away  90    0   3
41  2023-02-18  Sat       Premier League     Home  27    0   1
42  2023-02-26  Sun       Premier League     Away  90    1   0
43  2023-03-04  Sat       Premier League     Home  90    0   3
44  2023-03-07  Tue         Champions Lg     Home  90    0   3
45  2023-03-11  Sat       Premier League     Away  90    0   3
46  2023-03-18  Sat       Premier League     Home  90    0   3
48  2023-04-01  Sat       Premier League     Home  90    0   1
49  2023-04-04  Tue       Premier League     Home  90    0   2
50  2023-04-08  Sat       Premier League     Away  60    0   0
51  2023-04-12  Wed         Champions Lg     Away  26    0   1
53  2023-04-18  Tue         Champions Lg     Home  76    0   0
55  2023-05-02  Tue       Premier League     Away  45    0   0
56  2023-05-06  Sat       Premier League     Away  83    0   1
57  2023-05-13  Sat       Premier League     Home  18    0   0
58  2023-05-21  Sun       Premier League     Away  84    1   3
59  2023-05-25  Thu       Premier League     Away  63    0   2
60  2023-05-28  Sun       Premier League     Home  58    0   0

In [181]:
cleaned_df["Fls"] = pd.to_numeric(cleaned_df["Fls"])

In [182]:
cleaned_df["Min"] = pd.to_numeric(cleaned_df["Min"])

In [183]:
cleaned_df = cleaned_df.loc[cleaned_df["Min"] >= 60]